gormlog: true

log:
  logger_level: DEBUG #
  logger_file: log
  with_max_age: 7*24h #文件最大保存时间
  with_rotation_count: 5 #设置文件清理前最多保存的个数。
  with_rotation_time: 24h #日志切割时间间隔

nft:
  apiKey: "Z242j0W70266Z027i4K8H1c429A3t2g"
  apiSecret: "t2f2A0Y7X2h6v0i7h4q8j1E4n9o3d2f"
  domain: "https://stage.apis.avata.bianjie.ai"
  api:
    url:
      # 创建链账户
      create_account: "/v1beta1/account"
      # 批量创建链账户
      create_account_batch: "/v1beta1/accounts"
      # 查询链账户
      query_account: "/v1beta1/accounts"
      # 查询链账户操作记录
      query_account_history: "/v1beta1/accounts/history"
      # 上链交易结果查询
      query_task: "/v1beta1/tx/{task_id}"
      # 创建 NFT 类别
      create_nft_classes: "/v1beta1/nft/classes"
      # 查询 NFT 类别
      query_nft_classes: "/v1beta1/nft/classes"
      # 查询 NFT 类别详情
      query_nft_classes_detail: "/v1beta1/nft/classes/{id}"
      # 转让 NFT 类别
      transfers_nft_classes: "/v1beta1/nft/class-transfers/{class_id}/{owner}"
      # 发行 NFT
      create_nft: "/v1beta1/nft/nfts/{class_id}"
      # 转让 NFT
      transfers_nft: "/v1beta1/nft/nft-transfers/{class_id}/{owner}/{nft_id}"
      # 编辑 NFT
      edit_nft: "/v1beta1/nft/nfts/{class_id}/{owner}/{nft_id}"
      # 销毁 NFT
      destroy_nft: "/v1beta1/nft/nfts/{class_id}/{owner}/{nft_id}"
      # 查询 NFT
      query_nft: "/v1beta1/nft/nfts"
      # 查询 NFT 详情
      query_nft_detail: "/v1beta1/nft/nfts/{class_id}/{nft_id}"
      # 查询 NFT 操作记录
      query_nft_history: "/v1beta1/nft/nfts/{class_id}/{nft_id}/history"
      # 购买能量值/业务费
      buy_orders: "/v1beta1/orders"
      # 查询能量值/业务费购买结果列表
      query_orders: "/v1beta1/orders"
      # 查询能量值/业务费购买结果
      query_orders_result: "/v1beta1/orders/{order_id}"
